
services:
  ps-postgres:
    image: postgres:17.0-bookworm
    container_name: ps-postgres
    ports:
      - "5555:5432"
    env_file:
      - .env.local
    volumes:
      - ps-postgres-vol:/var/lib/postgresql/data

  ps-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: ps-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env.local
    ports:
      - "9200:9200"

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    env_file:
      - .env.local

volumes:
  ps-postgres-vol:
