
services:
  postgres:
    image: postgres:16.3-bookworm
    container_name: mss-pg16
    ports:
      - "5555:5432"
    env_file:
      - .env.local
    volumes:
      - mss-postgres-vol:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0.12
    container_name: mss-mongo7
    ports:
      - "27018:27017"
    env_file:
      - .env.local
    volumes:
      - mss-mongo-vol:/data/db
      - ./scripts/mongodb:/docker-entrypoint-initdb.d

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    env_file:
      - .env.local

volumes:
  mss-postgres-vol:
  mss-mongo-vol:
